### PR TITLE
CodeAnalysisJob gets files from UnitTestsJob(UnitTestsJob build number) not from UnitTestsJob(BuildAppJob build number)

### LINKED ISSUE #33: Failure case due to copy issues
The Reference Application Code Analysis job copies from the Reference_Application_Unit_Tests using the build number of the Reference_Application_Build job.  This will fail as soon as the Reference_Application_Build has failed once and the build number of the Reference_Application_Build job is higher than the highest Reference_Application_Unit_Tests job.

### PR DESCRIPTION
**Pull request by Janhout**
this commit fixes #33

### CODE REVIEW

**Comment by deors** [comment]
Did this one get merged? It is failing since long time, and still currently happening whenever a build job fails and will keep failing all the pipes unless you remove and recreate it from the cartridge.

**Comment by anton-kasperovich** [comment]
@deors no, it wasn't merged and @Janhout closed PR, so I can't actually do anything about it, but just suggest to recreate...

**Comment by deors** [comment]
@anton-kasperovich , yes this was closed, but @Janhout recreated it as #37 with all tests green

**Comment by anton-kasperovich** [comment]
@deors yeah, now it's clear, thank you, accepted.

**Pull request closed without merging**
